name: ptx-boa
channels:
  - defaults
  - conda-forge
dependencies:
  - black==23.1.0
  - flake8==5.0.4
  - ipython==8.9.0
  - isort==5.12.0
  - pip==22.3.1
  - pre-commit==2.20.0
  - pylint==2.17.3
  - pytest==7.1.2
  - python==3.10.8
