# -*- coding: utf-8 -*-
"""DO NOT EDIT (created by _update_static.py)."""

from typing import Literal

YearType = Literal["2030", "2040"]
YearValues = ["2030", "2040"]


ParameterRangeType = Literal["high", "low", "medium"]
ParameterRangeValues = ["high", "low", "medium"]


SourceRegionCodeType = Literal[
    "ARE",
    "ARG",
    "ARG-BA",
    "ARG-CAT",
    "ARG-CBA",
    "ARG-CHA",
    "ARG-CHU",
    "ARG-COR",
    "ARG-CRB",
    "ARG-CRU",
    "ARG-EST",
    "ARG-FOR",
    "ARG-FUE",
    "ARG-JUJ",
    "ARG-LAR",
    "ARG-MEN",
    "ARG-MIS",
    "ARG-NEG",
    "ARG-NEU",
    "ARG-PAM",
    "ARG-RIO",
    "ARG-SAF",
    "ARG-SAJ",
    "ARG-SAL",
    "ARG-SAT",
    "ARG-TUC",
    "AUS",
    "BRA",
    "CHL",
    "CHN",
    "COL",
    "CRI",
    "DNK",
    "DZA",
    "EGY",
    "ESP",
    "IDN",
    "IND",
    "JOR",
    "KAZ",
    "KEN",
    "MAR",
    "MAR-BEN",
    "MAR-CAS",
    "MAR-DAK",
    "MAR-DRA",
    "MAR-FES",
    "MAR-GUE",
    "MAR-LAA",
    "MAR-LOR",
    "MAR-MAR",
    "MAR-RAB",
    "MAR-SOU",
    "MAR-TAN",
    "MEX",
    "MRT",
    "NAM",
    "NOR",
    "PER",
    "PRT",
    "RUS",
    "SAU",
    "SWE",
    "THA",
    "TUN",
    "UKR",
    "URY",
    "USA",
    "VNM",
    "ZAF",
    "ZAF-EC",
    "ZAF-FRS",
    "ZAF-GAU",
    "ZAF-KWA",
    "ZAF-LIM",
    "ZAF-MPU",
    "ZAF-NC",
    "ZAF-NW",
    "ZAF-WC",
]
SourceRegionCodeValues = [
    "ARE",
    "ARG",
    "ARG-BA",
    "ARG-CAT",
    "ARG-CBA",
    "ARG-CHA",
    "ARG-CHU",
    "ARG-COR",
    "ARG-CRB",
    "ARG-CRU",
    "ARG-EST",
    "ARG-FOR",
    "ARG-FUE",
    "ARG-JUJ",
    "ARG-LAR",
    "ARG-MEN",
    "ARG-MIS",
    "ARG-NEG",
    "ARG-NEU",
    "ARG-PAM",
    "ARG-RIO",
    "ARG-SAF",
    "ARG-SAJ",
    "ARG-SAL",
    "ARG-SAT",
    "ARG-TUC",
    "AUS",
    "BRA",
    "CHL",
    "CHN",
    "COL",
    "CRI",
    "DNK",
    "DZA",
    "EGY",
    "ESP",
    "IDN",
    "IND",
    "JOR",
    "KAZ",
    "KEN",
    "MAR",
    "MAR-BEN",
    "MAR-CAS",
    "MAR-DAK",
    "MAR-DRA",
    "MAR-FES",
    "MAR-GUE",
    "MAR-LAA",
    "MAR-LOR",
    "MAR-MAR",
    "MAR-RAB",
    "MAR-SOU",
    "MAR-TAN",
    "MEX",
    "MRT",
    "NAM",
    "NOR",
    "PER",
    "PRT",
    "RUS",
    "SAU",
    "SWE",
    "THA",
    "TUN",
    "UKR",
    "URY",
    "USA",
    "VNM",
    "ZAF",
    "ZAF-EC",
    "ZAF-FRS",
    "ZAF-GAU",
    "ZAF-KWA",
    "ZAF-LIM",
    "ZAF-MPU",
    "ZAF-NC",
    "ZAF-NW",
    "ZAF-WC",
]


TargetCountryCodeType = Literal[
    "CHN", "DEU", "ESP", "FRA", "IND", "JPN", "KOR", "NLD", "USA"
]
TargetCountryCodeValues = [
    "CHN",
    "DEU",
    "ESP",
    "FRA",
    "IND",
    "JPN",
    "KOR",
    "NLD",
    "USA",
]


SourceRegionNameType = Literal[
    "Algeria",
    "Argentina",
    "Argentina (Autonomous City of Buenos Aires)",
    "Argentina (Buenos Aires)",
    "Argentina (Catamarca)",
    "Argentina (Chaco)",
    "Argentina (Chubut)",
    "Argentina (Córdoba)",
    "Argentina (Corrientes)",
    "Argentina (Entre Ríos)",
    "Argentina (Formosa)",
    "Argentina (Jujuy)",
    "Argentina (La Pampa)",
    "Argentina (La Rioja)",
    "Argentina (Mendoza)",
    "Argentina (Misiones)",
    "Argentina (Neuquén)",
    "Argentina (Río Negro)",
    "Argentina (Salta)",
    "Argentina (San Juan)",
    "Argentina (San Luis)",
    "Argentina (Santa Cruz)",
    "Argentina (Santa Fe)",
    "Argentina (Santiago del Estero)",
    "Argentina (Tierra del Fuego, Antártida e Islas del Atlántico Sur)",
    "Argentina (Tucumán)",
    "Australia",
    "Brazil",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Denmark",
    "Egypt",
    "India",
    "Indonesia",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Mauritania",
    "Mexico",
    "Morocco",
    "Morocco (Béni Mellal-Khénifra)",
    "Morocco (Casablanca)",
    "Morocco (Dakhla-Oued Ed-Dahab)",
    "Morocco (Drâa-Tafilalet)",
    "Morocco (Fès-Meknès)",
    "Morocco (Guelmim-Oued Noun)",
    "Morocco (L´oriental)",
    "Morocco (Laâyoune-Sakia El Hamra)",
    "Morocco (Marrakech-Safi)",
    "Morocco (Rabat-Salé-Kénitra)",
    "Morocco (Souss-Massa)",
    "Morocco (Tangier)",
    "Namibia",
    "Norway",
    "Peru",
    "Portugal",
    "Russia",
    "Saudi Arabia",
    "South Africa",
    "South Africa (East Cape)",
    "South Africa (Free State)",
    "South Africa (Gauteng)",
    "South Africa (KwaZulu-Natal)",
    "South Africa (Limpopo)",
    "South Africa (Mpumalanga)",
    "South Africa (North West)",
    "South Africa (Northern Cape)",
    "South Africa (Western Cape)",
    "Spain",
    "Sweden",
    "Thailand",
    "Tunisia",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "USA",
    "Vietnam",
]
SourceRegionNameValues = [
    "Algeria",
    "Argentina",
    "Argentina (Autonomous City of Buenos Aires)",
    "Argentina (Buenos Aires)",
    "Argentina (Catamarca)",
    "Argentina (Chaco)",
    "Argentina (Chubut)",
    "Argentina (Córdoba)",
    "Argentina (Corrientes)",
    "Argentina (Entre Ríos)",
    "Argentina (Formosa)",
    "Argentina (Jujuy)",
    "Argentina (La Pampa)",
    "Argentina (La Rioja)",
    "Argentina (Mendoza)",
    "Argentina (Misiones)",
    "Argentina (Neuquén)",
    "Argentina (Río Negro)",
    "Argentina (Salta)",
    "Argentina (San Juan)",
    "Argentina (San Luis)",
    "Argentina (Santa Cruz)",
    "Argentina (Santa Fe)",
    "Argentina (Santiago del Estero)",
    "Argentina (Tierra del Fuego, Antártida e Islas del Atlántico Sur)",
    "Argentina (Tucumán)",
    "Australia",
    "Brazil",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Denmark",
    "Egypt",
    "India",
    "Indonesia",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Mauritania",
    "Mexico",
    "Morocco",
    "Morocco (Béni Mellal-Khénifra)",
    "Morocco (Casablanca)",
    "Morocco (Dakhla-Oued Ed-Dahab)",
    "Morocco (Drâa-Tafilalet)",
    "Morocco (Fès-Meknès)",
    "Morocco (Guelmim-Oued Noun)",
    "Morocco (L´oriental)",
    "Morocco (Laâyoune-Sakia El Hamra)",
    "Morocco (Marrakech-Safi)",
    "Morocco (Rabat-Salé-Kénitra)",
    "Morocco (Souss-Massa)",
    "Morocco (Tangier)",
    "Namibia",
    "Norway",
    "Peru",
    "Portugal",
    "Russia",
    "Saudi Arabia",
    "South Africa",
    "South Africa (East Cape)",
    "South Africa (Free State)",
    "South Africa (Gauteng)",
    "South Africa (KwaZulu-Natal)",
    "South Africa (Limpopo)",
    "South Africa (Mpumalanga)",
    "South Africa (North West)",
    "South Africa (Northern Cape)",
    "South Africa (Western Cape)",
    "Spain",
    "Sweden",
    "Thailand",
    "Tunisia",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "USA",
    "Vietnam",
]


TargetCountryNameType = Literal[
    "China",
    "France",
    "Germany",
    "India",
    "Japan",
    "Netherlands",
    "South Korea",
    "Spain",
    "USA",
]
TargetCountryNameValues = [
    "China",
    "France",
    "Germany",
    "India",
    "Japan",
    "Netherlands",
    "South Korea",
    "Spain",
    "USA",
]


ProcessCodeType = Literal[
    "AEL-EL",
    "ATR",
    "CH3OHREC",
    "CH3OH-S",
    "CH3OH-SB",
    "CH3OHSYN",
    "CH4-COMP",
    "CH4-LIQ",
    "CH4-P-L",
    "CH4-P-LR",
    "CH4-P-S",
    "CH4-P-SR",
    "CH4-RGAS",
    "CH4-S",
    "CH4-SB",
    "CH4SYN",
    "DAC",
    "DESAL",
    "DRI",
    "DRI-S",
    "DRI-SB",
    "EFUELSYN",
    "EL-STR",
    "EL-TRANS",
    "H2-COMP",
    "H2-LIQ",
    "H2-P-L",
    "H2-P-LR",
    "H2-P-S",
    "H2-P-SR",
    "H2-RGAS",
    "H2-S",
    "H2-SB",
    "H2-STR",
    "LOHC-CON",
    "LOHC-REC",
    "LOHC-S",
    "LOHC-SB",
    "NH3-REC",
    "NH3-S",
    "NH3-SB",
    "NH3SYN",
    "PEM-EL",
    "PV-FIX",
    "PV-TRK",
    "REGASATR",
    "RES-HYBR",
    "SOEC-EL",
    "SYN-S",
    "SYN-SB",
    "WIND-OFF",
    "WIND-ON",
]
ProcessCodeValues = [
    "AEL-EL",
    "ATR",
    "CH3OHREC",
    "CH3OH-S",
    "CH3OH-SB",
    "CH3OHSYN",
    "CH4-COMP",
    "CH4-LIQ",
    "CH4-P-L",
    "CH4-P-LR",
    "CH4-P-S",
    "CH4-P-SR",
    "CH4-RGAS",
    "CH4-S",
    "CH4-SB",
    "CH4SYN",
    "DAC",
    "DESAL",
    "DRI",
    "DRI-S",
    "DRI-SB",
    "EFUELSYN",
    "EL-STR",
    "EL-TRANS",
    "H2-COMP",
    "H2-LIQ",
    "H2-P-L",
    "H2-P-LR",
    "H2-P-S",
    "H2-P-SR",
    "H2-RGAS",
    "H2-S",
    "H2-SB",
    "H2-STR",
    "LOHC-CON",
    "LOHC-REC",
    "LOHC-S",
    "LOHC-SB",
    "NH3-REC",
    "NH3-S",
    "NH3-SB",
    "NH3SYN",
    "PEM-EL",
    "PV-FIX",
    "PV-TRK",
    "REGASATR",
    "RES-HYBR",
    "SOEC-EL",
    "SYN-S",
    "SYN-SB",
    "WIND-OFF",
    "WIND-ON",
]


FlowCodeType = Literal[
    "BFUEL-L",
    "CH3OH-L",
    "CH4-G",
    "CH4-L",
    "CHX-L",
    "CO2-G",
    "C-S",
    "DRI-S",
    "EL",
    "H2-G",
    "H2-L",
    "H2O-L",
    "HEAT",
    "LOHC-L",
    "N2-G",
    "NH3-L",
]
FlowCodeValues = [
    "BFUEL-L",
    "CH3OH-L",
    "CH4-G",
    "CH4-L",
    "CHX-L",
    "CO2-G",
    "C-S",
    "DRI-S",
    "EL",
    "H2-G",
    "H2-L",
    "H2O-L",
    "HEAT",
    "LOHC-L",
    "N2-G",
    "NH3-L",
]


ParameterCodeType = Literal[
    "CALOR",
    "CAPEX",
    "CAP-T",
    "CONV",
    "DST-S-D",
    "DST-S-DP",
    "EFF",
    "FLH",
    "LIFETIME",
    "LOSS-T",
    "OPEX-F",
    "OPEX-O",
    "OPEX-T",
    "RE-POT",
    "SEASHARE",
    "SPECCOST",
    "WACC",
]
ParameterCodeValues = [
    "CALOR",
    "CAPEX",
    "CAP-T",
    "CONV",
    "DST-S-D",
    "DST-S-DP",
    "EFF",
    "FLH",
    "LIFETIME",
    "LOSS-T",
    "OPEX-F",
    "OPEX-O",
    "OPEX-T",
    "RE-POT",
    "SEASHARE",
    "SPECCOST",
    "WACC",
]


ParameterNameType = Literal[
    "calorific values",
    "CAPEX",
    "conversion factors",
    "efficiency",
    "full load hours",
    "interest rate",
    "levelized costs",
    "lifetime / amortization period",
    "losses (own fuel, transport)",
    "OPEX (fix)",
    "OPEX (other variable)",
    "pipeline distance",
    "RE potential",
    "sea share of pipeline distance",
    "shipping distance",
    "specific costs",
    "transport capacity",
]
ParameterNameValues = [
    "calorific values",
    "CAPEX",
    "conversion factors",
    "efficiency",
    "full load hours",
    "interest rate",
    "levelized costs",
    "lifetime / amortization period",
    "losses (own fuel, transport)",
    "OPEX (fix)",
    "OPEX (other variable)",
    "pipeline distance",
    "RE potential",
    "sea share of pipeline distance",
    "shipping distance",
    "specific costs",
    "transport capacity",
]


ChainNameType = Literal[
    "Ammonia (AEL)",
    "Ammonia (AEL) + reconv. to H2",
    "Ammonia (PEM)",
    "Ammonia (PEM) + reconv. to H2",
    "Ammonia (SEOC)",
    "Ammonia (SEOC) + reconv. to H2",
    "FT e-fuels (AEL)",
    "FT e-fuels (PEM)",
    "FT e-fuels (SEOC)",
    "Green Iron (AEL)",
    "Green Iron (PEM)",
    "Green Iron (SEOC)",
    "Hydrogen (AEL)",
    "Hydrogen (PEM)",
    "Hydrogen (SEOC)",
    "LOHC (AEL)",
    "LOHC (PEM)",
    "LOHC (SEOC)",
    "Methane (AEL)",
    "Methane (AEL) + reconv. to H2",
    "Methane (PEM)",
    "Methane (PEM) + reconv. to H2",
    "Methane (SEOC)",
    "Methane (SEOC) + reconv. to H2",
    "Methanol (AEL)",
    "Methanol (PEM)",
    "Methanol (SEOC)",
]
ChainNameValues = [
    "Ammonia (AEL)",
    "Ammonia (AEL) + reconv. to H2",
    "Ammonia (PEM)",
    "Ammonia (PEM) + reconv. to H2",
    "Ammonia (SEOC)",
    "Ammonia (SEOC) + reconv. to H2",
    "FT e-fuels (AEL)",
    "FT e-fuels (PEM)",
    "FT e-fuels (SEOC)",
    "Green Iron (AEL)",
    "Green Iron (PEM)",
    "Green Iron (SEOC)",
    "Hydrogen (AEL)",
    "Hydrogen (PEM)",
    "Hydrogen (SEOC)",
    "LOHC (AEL)",
    "LOHC (PEM)",
    "LOHC (SEOC)",
    "Methane (AEL)",
    "Methane (AEL) + reconv. to H2",
    "Methane (PEM)",
    "Methane (PEM) + reconv. to H2",
    "Methane (SEOC)",
    "Methane (SEOC) + reconv. to H2",
    "Methanol (AEL)",
    "Methanol (PEM)",
    "Methanol (SEOC)",
]


ScenarioType = Literal[
    "2030 (high)",
    "2030 (low)",
    "2030 (medium)",
    "2040 (high)",
    "2040 (low)",
    "2040 (medium)",
]
ScenarioValues = [
    "2030 (high)",
    "2030 (low)",
    "2030 (medium)",
    "2040 (high)",
    "2040 (low)",
    "2040 (medium)",
]


ResultClassType = Literal[
    "Carbon",
    "Derivate production",
    "Electricity and H2 storage",
    "Electricity generation",
    "Electrolysis",
    "HEAT",
    "Transportation (Pipeline)",
    "Transportation (Ship)",
    "Water",
]
ResultClassValues = [
    "Carbon",
    "Derivate production",
    "Electricity and H2 storage",
    "Electricity generation",
    "Electrolysis",
    "HEAT",
    "Transportation (Pipeline)",
    "Transportation (Ship)",
    "Water",
]


SecProcCO2Type = Literal["Direct Air Capture"]
SecProcCO2Values = ["Direct Air Capture"]


SecProcH2OType = Literal["Sea Water desalination"]
SecProcH2OValues = ["Sea Water desalination"]


ResGenType = Literal[
    "PV tilted", "PV tracking", "Wind-PV-Hybrid", "Wind Offshore", "Wind Onshore"
]
ResGenValues = [
    "PV tilted",
    "PV tracking",
    "Wind-PV-Hybrid",
    "Wind Offshore",
    "Wind Onshore",
]


ProcessCodeResType = Literal["PV-FIX", "PV-TRK", "RES-HYBR", "WIND-OFF", "WIND-ON"]
ProcessCodeResValues = ["PV-FIX", "PV-TRK", "RES-HYBR", "WIND-OFF", "WIND-ON"]


DimensionType = Literal[
    "scenario",
    "chain",
    "region",
    "country",
    "transport",
    "output_unit",
    "flow",
    "process",
    "secproc_co2",
    "secproc_water",
    "res_gen",
]
DimensionValues = [
    "scenario",
    "chain",
    "region",
    "country",
    "transport",
    "output_unit",
    "flow",
    "process",
    "secproc_co2",
    "secproc_water",
    "res_gen",
]


ProcessStepType = Literal[
    "EL_STR",
    "ELY",
    "H2_STR",
    "DERIV",
    "PRE_SHP",
    "PRE_PPL",
    "POST_SHP",
    "POST_PPL",
    "SHP",
    "SHP-OWN",
    "PPLS",
    "PPL",
    "PPLX",
    "PPLR",
]
ProcessStepValues = [
    "EL_STR",
    "ELY",
    "H2_STR",
    "DERIV",
    "PRE_SHP",
    "PRE_PPL",
    "POST_SHP",
    "POST_PPL",
    "SHP",
    "SHP-OWN",
    "PPLS",
    "PPL",
    "PPLX",
    "PPLR",
]


ResultCostType = Literal["CAPEX", "OPEX", "FLOW", "LC"]
ResultCostValues = ["CAPEX", "OPEX", "FLOW", "LC"]


TransportType = Literal["Ship", "Pipeline"]
TransportValues = ["Ship", "Pipeline"]


OutputUnitType = Literal["USD/MWh", "USD/t"]
OutputUnitValues = ["USD/MWh", "USD/t"]
