"""DO NOT EDIT (created by static/_update.py)."""

from typing import Literal

YearType = Literal["2030", "2040"]
YearValues: list[YearType] = ["2030", "2040"]


ParameterRangeType = Literal["high", "low", "medium"]
ParameterRangeValues: list[ParameterRangeType] = ["high", "low", "medium"]


SourceRegionCodeType = Literal[
    "ARE",
    "ARG",
    "ARG-BA",
    "ARG-CAT",
    "ARG-CBA",
    "ARG-CHA",
    "ARG-CHU",
    "ARG-COR",
    "ARG-CRB",
    "ARG-CRU",
    "ARG-EST",
    "ARG-FOR",
    "ARG-FUE",
    "ARG-JUJ",
    "ARG-LAR",
    "ARG-MEN",
    "ARG-MIS",
    "ARG-NEG",
    "ARG-NEU",
    "ARG-PAM",
    "ARG-RIO",
    "ARG-SAF",
    "ARG-SAJ",
    "ARG-SAL",
    "ARG-SAT",
    "ARG-TUC",
    "AUS",
    "BRA",
    "CHL",
    "CHN",
    "COL",
    "CRI",
    "DEU",
    "DNK",
    "DZA",
    "EGY",
    "ESP",
    "FRA",
    "IDN",
    "IND",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KOR",
    "MAR",
    "MAR-BEN",
    "MAR-CAS",
    "MAR-DAK",
    "MAR-DRA",
    "MAR-FES",
    "MAR-GUE",
    "MAR-LAA",
    "MAR-LOR",
    "MAR-MAR",
    "MAR-RAB",
    "MAR-SOU",
    "MAR-TAN",
    "MEX",
    "MRT",
    "MYS",
    "NAM",
    "NLD",
    "NOR",
    "OMN",
    "PAK",
    "PER",
    "PRT",
    "QAT",
    "RUS",
    "SAU",
    "SWE",
    "THA",
    "TUN",
    "UKR",
    "URY",
    "USA",
    "VNM",
    "ZAF",
    "ZAF-EC",
    "ZAF-FRS",
    "ZAF-GAU",
    "ZAF-KWA",
    "ZAF-LIM",
    "ZAF-MPU",
    "ZAF-NC",
    "ZAF-NW",
    "ZAF-WC",
]
SourceRegionCodeValues: list[SourceRegionCodeType] = [
    "ARE",
    "ARG",
    "ARG-BA",
    "ARG-CAT",
    "ARG-CBA",
    "ARG-CHA",
    "ARG-CHU",
    "ARG-COR",
    "ARG-CRB",
    "ARG-CRU",
    "ARG-EST",
    "ARG-FOR",
    "ARG-FUE",
    "ARG-JUJ",
    "ARG-LAR",
    "ARG-MEN",
    "ARG-MIS",
    "ARG-NEG",
    "ARG-NEU",
    "ARG-PAM",
    "ARG-RIO",
    "ARG-SAF",
    "ARG-SAJ",
    "ARG-SAL",
    "ARG-SAT",
    "ARG-TUC",
    "AUS",
    "BRA",
    "CHL",
    "CHN",
    "COL",
    "CRI",
    "DEU",
    "DNK",
    "DZA",
    "EGY",
    "ESP",
    "FRA",
    "IDN",
    "IND",
    "JOR",
    "JPN",
    "KAZ",
    "KEN",
    "KOR",
    "MAR",
    "MAR-BEN",
    "MAR-CAS",
    "MAR-DAK",
    "MAR-DRA",
    "MAR-FES",
    "MAR-GUE",
    "MAR-LAA",
    "MAR-LOR",
    "MAR-MAR",
    "MAR-RAB",
    "MAR-SOU",
    "MAR-TAN",
    "MEX",
    "MRT",
    "MYS",
    "NAM",
    "NLD",
    "NOR",
    "OMN",
    "PAK",
    "PER",
    "PRT",
    "QAT",
    "RUS",
    "SAU",
    "SWE",
    "THA",
    "TUN",
    "UKR",
    "URY",
    "USA",
    "VNM",
    "ZAF",
    "ZAF-EC",
    "ZAF-FRS",
    "ZAF-GAU",
    "ZAF-KWA",
    "ZAF-LIM",
    "ZAF-MPU",
    "ZAF-NC",
    "ZAF-NW",
    "ZAF-WC",
]


TargetCountryCodeType = Literal[
    "BRA", "CHN", "DEU", "ESP", "FRA", "IND", "JPN", "KOR", "NLD", "THA", "USA"
]
TargetCountryCodeValues: list[TargetCountryCodeType] = [
    "BRA",
    "CHN",
    "DEU",
    "ESP",
    "FRA",
    "IND",
    "JPN",
    "KOR",
    "NLD",
    "THA",
    "USA",
]


SourceRegionNameType = Literal[
    "Algeria",
    "Argentina",
    "Argentina (Autonomous City of Buenos Aires)",
    "Argentina (Buenos Aires)",
    "Argentina (Catamarca)",
    "Argentina (Chaco)",
    "Argentina (Chubut)",
    "Argentina (Córdoba)",
    "Argentina (Corrientes)",
    "Argentina (Entre Ríos)",
    "Argentina (Formosa)",
    "Argentina (Jujuy)",
    "Argentina (La Pampa)",
    "Argentina (La Rioja)",
    "Argentina (Mendoza)",
    "Argentina (Misiones)",
    "Argentina (Neuquén)",
    "Argentina (Río Negro)",
    "Argentina (Salta)",
    "Argentina (San Juan)",
    "Argentina (San Luis)",
    "Argentina (Santa Cruz)",
    "Argentina (Santa Fe)",
    "Argentina (Santiago del Estero)",
    "Argentina (Tierra del Fuego, Antártida e Islas del Atlántico Sur)",
    "Argentina (Tucumán)",
    "Australia",
    "Brazil",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Denmark",
    "Egypt",
    "France",
    "Germany",
    "India",
    "Indonesia",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Malaysia",
    "Mauritania",
    "Mexico",
    "Morocco",
    "Morocco (Béni Mellal-Khénifra)",
    "Morocco (Casablanca)",
    "Morocco (Dakhla-Oued Ed-Dahab)",
    "Morocco (Drâa-Tafilalet)",
    "Morocco (Fès-Meknès)",
    "Morocco (Guelmim-Oued Noun)",
    "Morocco (L´oriental)",
    "Morocco (Laâyoune-Sakia El Hamra)",
    "Morocco (Marrakech-Safi)",
    "Morocco (Rabat-Salé-Kénitra)",
    "Morocco (Souss-Massa)",
    "Morocco (Tangier)",
    "Namibia",
    "Netherlands",
    "Norway",
    "Oman",
    "Pakistan",
    "Peru",
    "Portugal",
    "Qatar",
    "Russia",
    "Saudi Arabia",
    "South Africa",
    "South Africa (East Cape)",
    "South Africa (Free State)",
    "South Africa (Gauteng)",
    "South Africa (KwaZulu-Natal)",
    "South Africa (Limpopo)",
    "South Africa (Mpumalanga)",
    "South Africa (North West)",
    "South Africa (Northern Cape)",
    "South Africa (Western Cape)",
    "South Korea",
    "Spain",
    "Sweden",
    "Thailand",
    "Tunisia",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "USA",
    "Vietnam",
]
SourceRegionNameValues: list[SourceRegionNameType] = [
    "Algeria",
    "Argentina",
    "Argentina (Autonomous City of Buenos Aires)",
    "Argentina (Buenos Aires)",
    "Argentina (Catamarca)",
    "Argentina (Chaco)",
    "Argentina (Chubut)",
    "Argentina (Córdoba)",
    "Argentina (Corrientes)",
    "Argentina (Entre Ríos)",
    "Argentina (Formosa)",
    "Argentina (Jujuy)",
    "Argentina (La Pampa)",
    "Argentina (La Rioja)",
    "Argentina (Mendoza)",
    "Argentina (Misiones)",
    "Argentina (Neuquén)",
    "Argentina (Río Negro)",
    "Argentina (Salta)",
    "Argentina (San Juan)",
    "Argentina (San Luis)",
    "Argentina (Santa Cruz)",
    "Argentina (Santa Fe)",
    "Argentina (Santiago del Estero)",
    "Argentina (Tierra del Fuego, Antártida e Islas del Atlántico Sur)",
    "Argentina (Tucumán)",
    "Australia",
    "Brazil",
    "Chile",
    "China",
    "Colombia",
    "Costa Rica",
    "Denmark",
    "Egypt",
    "France",
    "Germany",
    "India",
    "Indonesia",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Malaysia",
    "Mauritania",
    "Mexico",
    "Morocco",
    "Morocco (Béni Mellal-Khénifra)",
    "Morocco (Casablanca)",
    "Morocco (Dakhla-Oued Ed-Dahab)",
    "Morocco (Drâa-Tafilalet)",
    "Morocco (Fès-Meknès)",
    "Morocco (Guelmim-Oued Noun)",
    "Morocco (L´oriental)",
    "Morocco (Laâyoune-Sakia El Hamra)",
    "Morocco (Marrakech-Safi)",
    "Morocco (Rabat-Salé-Kénitra)",
    "Morocco (Souss-Massa)",
    "Morocco (Tangier)",
    "Namibia",
    "Netherlands",
    "Norway",
    "Oman",
    "Pakistan",
    "Peru",
    "Portugal",
    "Qatar",
    "Russia",
    "Saudi Arabia",
    "South Africa",
    "South Africa (East Cape)",
    "South Africa (Free State)",
    "South Africa (Gauteng)",
    "South Africa (KwaZulu-Natal)",
    "South Africa (Limpopo)",
    "South Africa (Mpumalanga)",
    "South Africa (North West)",
    "South Africa (Northern Cape)",
    "South Africa (Western Cape)",
    "South Korea",
    "Spain",
    "Sweden",
    "Thailand",
    "Tunisia",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "USA",
    "Vietnam",
]


TargetCountryNameType = Literal[
    "Brazil",
    "China",
    "France",
    "Germany",
    "India",
    "Japan",
    "Netherlands",
    "South Korea",
    "Spain",
    "Thailand",
    "USA",
]
TargetCountryNameValues: list[TargetCountryNameType] = [
    "Brazil",
    "China",
    "France",
    "Germany",
    "India",
    "Japan",
    "Netherlands",
    "South Korea",
    "Spain",
    "Thailand",
    "USA",
]


ProcessCodeType = Literal[
    "AEL-EL",
    "ATR",
    "ATR_91%#B",
    "CCGT-CC#B",
    "CH3OH-S",
    "CH3OH-S#B",
    "CH3OH-SB",
    "CH3OH-SB#B",
    "CH3OHSYC#B",
    "CH3OHSYN",
    "CH3OHSYN#B",
    "CH4-COMP",
    "CH4-COMP#B",
    "CH4-LIQ",
    "CH4-LIQ#B",
    "CH4-P-L",
    "CH4-P-L#B",
    "CH4-P-LR",
    "CH4-P-LR#B",
    "CH4-P-S",
    "CH4-P-S#B",
    "CH4-P-SR",
    "CH4-P-SR#B",
    "CH4-RGAS",
    "CH4-RGAS#B",
    "CH4-S",
    "CH4-S#B",
    "CH4-SB",
    "CH4-SB#B",
    "CH4SYN",
    "CO2-INDF#B",
    "CO2-INDS#B",
    "CO2-T+S#B",
    "DAC",
    "DAC#B",
    "DESAL",
    "DRI",
    "DRI#B",
    "DRI-rotary#B",
    "DRI-SB",
    "DRI-SB#B",
    "EAF#B",
    "EFUELSYN",
    "EFUELSYN#B",
    "EFUELSYNC#B",
    "EL-STR",
    "H2-COMP",
    "H2-COMP#B",
    "H2-LIQ",
    "H2-LIQ#B",
    "H2-P-L",
    "H2-P-L#B",
    "H2-P-LR",
    "H2-P-LR#B",
    "H2-P-S",
    "H2-P-S#B",
    "H2-P-SR",
    "H2-P-SR#B",
    "H2-RGAS",
    "H2-RGAS#B",
    "H2-S",
    "H2-S#B",
    "H2-SB",
    "H2-SB#B",
    "H2-STR",
    "HEATPUMP#B",
    "LOHC-CON",
    "LOHC-REC",
    "LOHC-S",
    "LOHC-SB",
    "NG-DRI-C#B",
    "NG-PROD#B",
    "NH3-REC",
    "NH3-REC#B",
    "NH3-S",
    "NH3-S#B",
    "NH3-SB",
    "NH3-SB#B",
    "NH3SYN",
    "NH3SYN#B",
    "PEM-EL",
    "PV-FIX",
    "REGASATR",
    "RES-HYBR",
    "SMR_52%#B",
    "SMR_52%_BF#B",
    "SOEC-EL",
    "SYN-S",
    "SYN-S#B",
    "SYN-SB",
    "SYN-SB#B",
    "WIND-OFF",
    "WIND-ON",
]
ProcessCodeValues: list[ProcessCodeType] = [
    "AEL-EL",
    "ATR",
    "ATR_91%#B",
    "CCGT-CC#B",
    "CH3OH-S",
    "CH3OH-S#B",
    "CH3OH-SB",
    "CH3OH-SB#B",
    "CH3OHSYC#B",
    "CH3OHSYN",
    "CH3OHSYN#B",
    "CH4-COMP",
    "CH4-COMP#B",
    "CH4-LIQ",
    "CH4-LIQ#B",
    "CH4-P-L",
    "CH4-P-L#B",
    "CH4-P-LR",
    "CH4-P-LR#B",
    "CH4-P-S",
    "CH4-P-S#B",
    "CH4-P-SR",
    "CH4-P-SR#B",
    "CH4-RGAS",
    "CH4-RGAS#B",
    "CH4-S",
    "CH4-S#B",
    "CH4-SB",
    "CH4-SB#B",
    "CH4SYN",
    "CO2-INDF#B",
    "CO2-INDS#B",
    "CO2-T+S#B",
    "DAC",
    "DAC#B",
    "DESAL",
    "DRI",
    "DRI#B",
    "DRI-rotary#B",
    "DRI-SB",
    "DRI-SB#B",
    "EAF#B",
    "EFUELSYN",
    "EFUELSYN#B",
    "EFUELSYNC#B",
    "EL-STR",
    "H2-COMP",
    "H2-COMP#B",
    "H2-LIQ",
    "H2-LIQ#B",
    "H2-P-L",
    "H2-P-L#B",
    "H2-P-LR",
    "H2-P-LR#B",
    "H2-P-S",
    "H2-P-S#B",
    "H2-P-SR",
    "H2-P-SR#B",
    "H2-RGAS",
    "H2-RGAS#B",
    "H2-S",
    "H2-S#B",
    "H2-SB",
    "H2-SB#B",
    "H2-STR",
    "HEATPUMP#B",
    "LOHC-CON",
    "LOHC-REC",
    "LOHC-S",
    "LOHC-SB",
    "NG-DRI-C#B",
    "NG-PROD#B",
    "NH3-REC",
    "NH3-REC#B",
    "NH3-S",
    "NH3-S#B",
    "NH3-SB",
    "NH3-SB#B",
    "NH3SYN",
    "NH3SYN#B",
    "PEM-EL",
    "PV-FIX",
    "REGASATR",
    "RES-HYBR",
    "SMR_52%#B",
    "SMR_52%_BF#B",
    "SOEC-EL",
    "SYN-S",
    "SYN-S#B",
    "SYN-SB",
    "SYN-SB#B",
    "WIND-OFF",
    "WIND-ON",
]


FlowCodeType = Literal[
    "B-DRI-S",
    "BFUEL-L",
    "CH3OH-L",
    "CH4-G",
    "CH4-L",
    "CHX-L",
    "CO2-C",
    "CO2-DAC",
    "CO2-G",
    "CO2-INDF",
    "CO2-INDS",
    "DIESEL-L",
    "DRI-S",
    "EL",
    "H2-G",
    "H2-L",
    "H2O-L",
    "HEAT",
    "IOF-S",
    "IOP-S",
    "LOHC-L",
    "N2-G",
    "NG-G",
    "NG-L",
    "NH3-L",
    "STL-S",
]
FlowCodeValues: list[FlowCodeType] = [
    "B-DRI-S",
    "BFUEL-L",
    "CH3OH-L",
    "CH4-G",
    "CH4-L",
    "CHX-L",
    "CO2-C",
    "CO2-DAC",
    "CO2-G",
    "CO2-INDF",
    "CO2-INDS",
    "DIESEL-L",
    "DRI-S",
    "EL",
    "H2-G",
    "H2-L",
    "H2O-L",
    "HEAT",
    "IOF-S",
    "IOP-S",
    "LOHC-L",
    "N2-G",
    "NG-G",
    "NG-L",
    "NH3-L",
    "STL-S",
]


ParameterCodeType = Literal[
    "CALOR",
    "CAPEX",
    "CAP-T",
    "CBOUND",
    "CH4SHARE",
    "CO2CPT-R",
    "CO2CPT-S",
    "CONV",
    "CONV-OT",
    "DST-S-D",
    "DST-S-DP",
    "EF_E",
    "EF_M",
    "EFF",
    "FLH",
    "LIFETIME",
    "LOSS",
    "LOSS-T",
    "OPEX-F",
    "OPEX-O",
    "OPEX-T",
    "SEASHARE",
    "SPECCOST",
    "WACC",
]
ParameterCodeValues: list[ParameterCodeType] = [
    "CALOR",
    "CAPEX",
    "CAP-T",
    "CBOUND",
    "CH4SHARE",
    "CO2CPT-R",
    "CO2CPT-S",
    "CONV",
    "CONV-OT",
    "DST-S-D",
    "DST-S-DP",
    "EF_E",
    "EF_M",
    "EFF",
    "FLH",
    "LIFETIME",
    "LOSS",
    "LOSS-T",
    "OPEX-F",
    "OPEX-O",
    "OPEX-T",
    "SEASHARE",
    "SPECCOST",
    "WACC",
]


ParameterNameType = Literal[
    "C bound in product",
    "calorific values",
    "CAPEX",
    "capture rate by flow",
    "CO2 for capture share",
    "conversion factors",
    "conversion factors (other fuel, transport)",
    "efficiency",
    "emission factor for emission balance",
    "emission factor for mass balance",
    "full load hours",
    "levelized costs",
    "lifetime / amortization period",
    "losses (own fuel)",
    "losses (own fuel, transport)",
    "methane share",
    "OPEX (fix)",
    "OPEX (other variable)",
    "pipeline distance",
    "sea share of pipeline distance",
    "shipping distance",
    "specific costs",
    "transport capacity",
    "WACC",
]
ParameterNameValues: list[ParameterNameType] = [
    "C bound in product",
    "calorific values",
    "CAPEX",
    "capture rate by flow",
    "CO2 for capture share",
    "conversion factors",
    "conversion factors (other fuel, transport)",
    "efficiency",
    "emission factor for emission balance",
    "emission factor for mass balance",
    "full load hours",
    "levelized costs",
    "lifetime / amortization period",
    "losses (own fuel)",
    "losses (own fuel, transport)",
    "methane share",
    "OPEX (fix)",
    "OPEX (other variable)",
    "pipeline distance",
    "sea share of pipeline distance",
    "shipping distance",
    "specific costs",
    "transport capacity",
    "WACC",
]


ChainType = Literal[
    "Ammonia (AEL)",
    "Ammonia (AEL) + reconv. to H2",
    "Ammonia (PEM)",
    "Ammonia (PEM) + reconv. to H2",
    "Ammonia (SOEC)",
    "Ammonia (SOEC) + reconv. to H2",
    "B-DRI-S__ATR_91%_DRI__prod_in_demand",
    "B-DRI-S__ATR_91%_DRI__prod_in_supply",
    "B-DRI-S__ATR_91%_DRI-rotary__prod_in_demand",
    "B-DRI-S__ATR_91%_DRI-rotary__prod_in_supply",
    "B-DRI-S__NG-DRI-C__prod_in_demand",
    "B-DRI-S__NG-DRI-C__prod_in_supply",
    "B-DRI-S__SMR_52%_BF_DRI__prod_in_demand",
    "B-DRI-S__SMR_52%_BF_DRI__prod_in_supply",
    "B-DRI-S__SMR_52%_BF_DRI-rotary__prod_in_demand",
    "B-DRI-S__SMR_52%_BF_DRI-rotary__prod_in_supply",
    "B-DRI-S__SMR_52%_DRI__prod_in_demand",
    "B-DRI-S__SMR_52%_DRI__prod_in_supply",
    "B-DRI-S__SMR_52%_DRI-rotary__prod_in_demand",
    "B-DRI-S__SMR_52%_DRI-rotary__prod_in_supply",
    "Blue Iron (blue)*",
    "CH3OH-L__ATR_91%_CH3OHSYN__prod_in_demand",
    "CH3OH-L__ATR_91%_CH3OHSYN__prod_in_supply",
    "CH3OH-L__CH3OHSYC__prod_in_demand",
    "CH3OH-L__CH3OHSYC__prod_in_supply",
    "CH3OH-L__SMR_52%_BF_CH3OHSYN__prod_in_demand",
    "CH3OH-L__SMR_52%_BF_CH3OHSYN__prod_in_supply",
    "CH3OH-L__SMR_52%_CH3OHSYN__prod_in_demand",
    "CH3OH-L__SMR_52%_CH3OHSYN__prod_in_supply",
    "CHX-L__ATR_91%_EFUELSYN__prod_in_demand",
    "CHX-L__ATR_91%_EFUELSYN__prod_in_supply",
    "CHX-L__EFUELSYNC__prod_in_demand",
    "CHX-L__EFUELSYNC__prod_in_supply",
    "CHX-L__SMR_52%_BF_EFUELSYN__prod_in_demand",
    "CHX-L__SMR_52%_BF_EFUELSYN__prod_in_supply",
    "CHX-L__SMR_52%_EFUELSYN__prod_in_demand",
    "CHX-L__SMR_52%_EFUELSYN__prod_in_supply",
    "FT e-fuels (AEL)",
    "FT e-fuels (PEM)",
    "FT e-fuels (SOEC)",
    "Green Iron (AEL)",
    "Green Iron (PEM)",
    "Green Iron (SOEC)",
    "H2-G__ATR_91%__prod_in_demand",
    "H2-G__ATR_91%__prod_in_supply",
    "H2-G__ATR_91%__prod_in_supply__transport_NH3-L",
    "H2-G__SMR_52%__prod_in_demand",
    "H2-G__SMR_52%__prod_in_supply",
    "H2-G__SMR_52%__prod_in_supply__transport_NH3-L",
    "H2-G__SMR_52%_BF__prod_in_demand",
    "H2-G__SMR_52%_BF__prod_in_supply",
    "H2-G__SMR_52%_BF__prod_in_supply__transport_NH3-L",
    "Hydrogen (AEL)",
    "Hydrogen (PEM)",
    "Hydrogen (SOEC)",
    "LOHC (AEL)",
    "LOHC (PEM)",
    "LOHC (SOEC)",
    "Methane (AEL)",
    "Methane (AEL) + reconv. to H2",
    "Methane (PEM)",
    "Methane (PEM) + reconv. to H2",
    "Methane (SOEC)",
    "Methane (SOEC) + reconv. to H2",
    "Methanol (AEL)",
    "Methanol (PEM)",
    "Methanol (SOEC)",
    "NH3-L__ATR_91%_NH3SYN__prod_in_demand",
    "NH3-L__ATR_91%_NH3SYN__prod_in_supply",
    "NH3-L__SMR_52%_BF_NH3SYN__prod_in_demand",
    "NH3-L__SMR_52%_BF_NH3SYN__prod_in_supply",
    "NH3-L__SMR_52%_NH3SYN__prod_in_demand",
    "NH3-L__SMR_52%_NH3SYN__prod_in_supply",
    "STL-S__ATR_91%_DRI_EAF__prod_in_demand",
    "STL-S__ATR_91%_DRI_EAF__prod_in_supply",
    "STL-S__ATR_91%_DRI-rotary_EAF__prod_in_demand",
    "STL-S__ATR_91%_DRI-rotary_EAF__prod_in_supply",
    "STL-S__NG-DRI-C_EAF__prod_in_demand",
    "STL-S__NG-DRI-C_EAF__prod_in_supply",
    "STL-S__SMR_52%_BF_DRI_EAF__prod_in_demand",
    "STL-S__SMR_52%_BF_DRI_EAF__prod_in_supply",
    "STL-S__SMR_52%_BF_DRI-rotary_EAF__prod_in_demand",
    "STL-S__SMR_52%_BF_DRI-rotary_EAF__prod_in_supply",
    "STL-S__SMR_52%_DRI_EAF__prod_in_demand",
    "STL-S__SMR_52%_DRI_EAF__prod_in_supply",
    "STL-S__SMR_52%_DRI-rotary_EAF__prod_in_demand",
    "STL-S__SMR_52%_DRI-rotary_EAF__prod_in_supply",
]
ChainValues: list[ChainType] = [
    "Ammonia (AEL)",
    "Ammonia (AEL) + reconv. to H2",
    "Ammonia (PEM)",
    "Ammonia (PEM) + reconv. to H2",
    "Ammonia (SOEC)",
    "Ammonia (SOEC) + reconv. to H2",
    "B-DRI-S__ATR_91%_DRI__prod_in_demand",
    "B-DRI-S__ATR_91%_DRI__prod_in_supply",
    "B-DRI-S__ATR_91%_DRI-rotary__prod_in_demand",
    "B-DRI-S__ATR_91%_DRI-rotary__prod_in_supply",
    "B-DRI-S__NG-DRI-C__prod_in_demand",
    "B-DRI-S__NG-DRI-C__prod_in_supply",
    "B-DRI-S__SMR_52%_BF_DRI__prod_in_demand",
    "B-DRI-S__SMR_52%_BF_DRI__prod_in_supply",
    "B-DRI-S__SMR_52%_BF_DRI-rotary__prod_in_demand",
    "B-DRI-S__SMR_52%_BF_DRI-rotary__prod_in_supply",
    "B-DRI-S__SMR_52%_DRI__prod_in_demand",
    "B-DRI-S__SMR_52%_DRI__prod_in_supply",
    "B-DRI-S__SMR_52%_DRI-rotary__prod_in_demand",
    "B-DRI-S__SMR_52%_DRI-rotary__prod_in_supply",
    "Blue Iron (blue)*",
    "CH3OH-L__ATR_91%_CH3OHSYN__prod_in_demand",
    "CH3OH-L__ATR_91%_CH3OHSYN__prod_in_supply",
    "CH3OH-L__CH3OHSYC__prod_in_demand",
    "CH3OH-L__CH3OHSYC__prod_in_supply",
    "CH3OH-L__SMR_52%_BF_CH3OHSYN__prod_in_demand",
    "CH3OH-L__SMR_52%_BF_CH3OHSYN__prod_in_supply",
    "CH3OH-L__SMR_52%_CH3OHSYN__prod_in_demand",
    "CH3OH-L__SMR_52%_CH3OHSYN__prod_in_supply",
    "CHX-L__ATR_91%_EFUELSYN__prod_in_demand",
    "CHX-L__ATR_91%_EFUELSYN__prod_in_supply",
    "CHX-L__EFUELSYNC__prod_in_demand",
    "CHX-L__EFUELSYNC__prod_in_supply",
    "CHX-L__SMR_52%_BF_EFUELSYN__prod_in_demand",
    "CHX-L__SMR_52%_BF_EFUELSYN__prod_in_supply",
    "CHX-L__SMR_52%_EFUELSYN__prod_in_demand",
    "CHX-L__SMR_52%_EFUELSYN__prod_in_supply",
    "FT e-fuels (AEL)",
    "FT e-fuels (PEM)",
    "FT e-fuels (SOEC)",
    "Green Iron (AEL)",
    "Green Iron (PEM)",
    "Green Iron (SOEC)",
    "H2-G__ATR_91%__prod_in_demand",
    "H2-G__ATR_91%__prod_in_supply",
    "H2-G__ATR_91%__prod_in_supply__transport_NH3-L",
    "H2-G__SMR_52%__prod_in_demand",
    "H2-G__SMR_52%__prod_in_supply",
    "H2-G__SMR_52%__prod_in_supply__transport_NH3-L",
    "H2-G__SMR_52%_BF__prod_in_demand",
    "H2-G__SMR_52%_BF__prod_in_supply",
    "H2-G__SMR_52%_BF__prod_in_supply__transport_NH3-L",
    "Hydrogen (AEL)",
    "Hydrogen (PEM)",
    "Hydrogen (SOEC)",
    "LOHC (AEL)",
    "LOHC (PEM)",
    "LOHC (SOEC)",
    "Methane (AEL)",
    "Methane (AEL) + reconv. to H2",
    "Methane (PEM)",
    "Methane (PEM) + reconv. to H2",
    "Methane (SOEC)",
    "Methane (SOEC) + reconv. to H2",
    "Methanol (AEL)",
    "Methanol (PEM)",
    "Methanol (SOEC)",
    "NH3-L__ATR_91%_NH3SYN__prod_in_demand",
    "NH3-L__ATR_91%_NH3SYN__prod_in_supply",
    "NH3-L__SMR_52%_BF_NH3SYN__prod_in_demand",
    "NH3-L__SMR_52%_BF_NH3SYN__prod_in_supply",
    "NH3-L__SMR_52%_NH3SYN__prod_in_demand",
    "NH3-L__SMR_52%_NH3SYN__prod_in_supply",
    "STL-S__ATR_91%_DRI_EAF__prod_in_demand",
    "STL-S__ATR_91%_DRI_EAF__prod_in_supply",
    "STL-S__ATR_91%_DRI-rotary_EAF__prod_in_demand",
    "STL-S__ATR_91%_DRI-rotary_EAF__prod_in_supply",
    "STL-S__NG-DRI-C_EAF__prod_in_demand",
    "STL-S__NG-DRI-C_EAF__prod_in_supply",
    "STL-S__SMR_52%_BF_DRI_EAF__prod_in_demand",
    "STL-S__SMR_52%_BF_DRI_EAF__prod_in_supply",
    "STL-S__SMR_52%_BF_DRI-rotary_EAF__prod_in_demand",
    "STL-S__SMR_52%_BF_DRI-rotary_EAF__prod_in_supply",
    "STL-S__SMR_52%_DRI_EAF__prod_in_demand",
    "STL-S__SMR_52%_DRI_EAF__prod_in_supply",
    "STL-S__SMR_52%_DRI-rotary_EAF__prod_in_demand",
    "STL-S__SMR_52%_DRI-rotary_EAF__prod_in_supply",
]


ScenarioType = Literal[
    "2030 (high)",
    "2030 (low)",
    "2030 (medium)",
    "2040 (high)",
    "2040 (low)",
    "2040 (medium)",
]
ScenarioValues: list[ScenarioType] = [
    "2030 (high)",
    "2030 (low)",
    "2030 (medium)",
    "2040 (high)",
    "2040 (low)",
    "2040 (medium)",
]


ResultClassType = Literal[
    "Carbon",
    "CO2 transport and storage",
    "Derivative production",
    "Electricity and H2 storage",
    "Electricity generation",
    "H2 production",
    "Heat",
    "Natural gas production",
    "Transportation (Pipeline)",
    "Transportation (Ship)",
    "Water",
]
ResultClassValues: list[ResultClassType] = [
    "Carbon",
    "CO2 transport and storage",
    "Derivative production",
    "Electricity and H2 storage",
    "Electricity generation",
    "H2 production",
    "Heat",
    "Natural gas production",
    "Transportation (Pipeline)",
    "Transportation (Ship)",
    "Water",
]


SecProcCO2Type = Literal[
    "CO2 from other industrial sources",
    "CO2 from hard-to-abate or sustainable sources",
    "Direct Air Capture",
    "Direct Air Capture (blue)",
]
SecProcCO2Values: list[SecProcCO2Type] = [
    "CO2 from other industrial sources",
    "CO2 from hard-to-abate or sustainable sources",
    "Direct Air Capture",
    "Direct Air Capture (blue)",
]


SecProcH2OType = Literal["Sea Water desalination"]
SecProcH2OValues: list[SecProcH2OType] = ["Sea Water desalination"]


SecProcHEATType = Literal["Large scale Heatpump (blue)"]
SecProcHEATValues: list[SecProcHEATType] = ["Large scale Heatpump (blue)"]


SecProcELType = Literal["Combined Cycle Gas Turbine with CCS (blue)"]
SecProcELValues: list[SecProcELType] = ["Combined Cycle Gas Turbine with CCS (blue)"]


SecProcCCSType = Literal["CO2 transport and storage (blue)"]
SecProcCCSValues: list[SecProcCCSType] = ["CO2 transport and storage (blue)"]


ResGenType = Literal["PV tilted", "Wind-PV-Hybrid", "Wind Offshore", "Wind Onshore"]
ResGenValues: list[ResGenType] = [
    "PV tilted",
    "Wind-PV-Hybrid",
    "Wind Offshore",
    "Wind Onshore",
]


ProcessCodeResType = Literal["PV-FIX", "RES-HYBR", "WIND-OFF", "WIND-ON"]
ProcessCodeResValues: list[ProcessCodeResType] = [
    "PV-FIX",
    "RES-HYBR",
    "WIND-OFF",
    "WIND-ON",
]


DimensionType = Literal[
    "scenario",
    "chain",
    "region",
    "country",
    "transport",
    "output_unit",
    "flow",
    "process",
    "secproc_co2",
    "secproc_water",
    "secproc_heat",
    "secproc_el",
    "secproc_ccs",
    "secproc_ccs_i",
    "res_gen",
    "parameter",
]
DimensionValues: list[DimensionType] = [
    "scenario",
    "chain",
    "region",
    "country",
    "transport",
    "output_unit",
    "flow",
    "process",
    "secproc_co2",
    "secproc_water",
    "secproc_heat",
    "secproc_el",
    "secproc_ccs",
    "secproc_ccs_i",
    "res_gen",
    "parameter",
]


ProcessStepType = Literal[
    "EL_STR",
    "ELY",
    "H2_STR",
    "DERIV",
    "DERIV2",
    "PRE_SHP",
    "SHP",
    "SHP_OWN",
    "POST_SHP",
    "PRE_PPL",
    "PPLS",
    "PPL",
    "PPLX",
    "PPLR",
    "POST_PPL",
    "ELY_I",
    "DERIV_I",
    "DERIV_I2",
]
ProcessStepValues: list[ProcessStepType] = [
    "EL_STR",
    "ELY",
    "H2_STR",
    "DERIV",
    "DERIV2",
    "PRE_SHP",
    "SHP",
    "SHP_OWN",
    "POST_SHP",
    "PRE_PPL",
    "PPLS",
    "PPL",
    "PPLX",
    "PPLR",
    "POST_PPL",
    "ELY_I",
    "DERIV_I",
    "DERIV_I2",
]


ResultCostType = Literal["CAPEX", "OPEX", "FLOW", "LC"]
ResultCostValues: list[ResultCostType] = ["CAPEX", "OPEX", "FLOW", "LC"]


TransportType = Literal["Ship", "Pipeline", "NONE"]
TransportValues: list[TransportType] = ["Ship", "Pipeline", "NONE"]


OutputUnitType = Literal["USD/MWh", "USD/t"]
OutputUnitValues: list[OutputUnitType] = ["USD/MWh", "USD/t"]


OutputUnitEmissionsType = Literal["gCO2e/MJ", "tCO2e/t", "NA"]
OutputUnitEmissionsValues: list[OutputUnitEmissionsType] = ["gCO2e/MJ", "tCO2e/t", "NA"]


ToolVersionColorType = Literal["blue", "green"]
ToolVersionColorValues: list[ToolVersionColorType] = ["blue", "green"]


ResultEmissionType = Literal["direct", "indirect"]
ResultEmissionValues: list[ResultEmissionType] = ["direct", "indirect"]


EmissionType = Literal["mass", "emission"]
EmissionValues: list[EmissionType] = ["mass", "emission"]


ResultGasType = Literal["CO2", "CH4"]
ResultGasValues: list[ResultGasType] = ["CO2", "CH4"]


DataQueryParameterType = Literal[
    "parameter_code",
    "process_code",
    "flow_code",
    "source_region_code",
    "target_country_code",
    "default",
    "use_user_data",
    "region",
    "process_res",
    "process_ely",
    "process_deriv",
    "process_flh",
]
DataQueryParameterValues: list[DataQueryParameterType] = [
    "parameter_code",
    "process_code",
    "flow_code",
    "source_region_code",
    "target_country_code",
    "default",
    "use_user_data",
    "region",
    "process_res",
    "process_ely",
    "process_deriv",
    "process_flh",
]
