[theme]
    primaryColor="#1A667B"
    backgroundColor="#f8f8f8"
    secondaryBackgroundColor="#F0F2F6"
    textColor="#262730"
    font="sans serif"

[client]
    toolbarMode = "minimal"

[logger]
    level="DEBUG"

[browser]
    gatherUsageStats = false
